### ISSUE TITLE
Multiple definition error

### ISSUE THREAD

**Issue by logankaser** [chusitoo/flatbush#2]
I get `multiple definition of 'flatbush::detail::calculateNumNodesPerLevel(unsigned int, unsigned int)'`
When I try to compile with flatbush, with includes in more than one file, is there a special way I'm meant to include it?

**Comment by chusitoo** [comment]
Hello and thanks for bringing this up.
There should be no special handling required to include this header, but I don't think I ever tested it `#include`d in more than a single file.
I'll have a fix for this shortly.

**Comment by chusitoo** [comment]
Fixed in commit 94fa07054fb2790b43eb55481134fd9fe3e58729

**Comment by logankaser** [comment]
Thanks, I'm using this and https://github.com/jlblancoc/nanoflann to accelerate geometric queries for a SQL-like thing I'm writing to search for things in HD digital maps at Zoox, thought you might like to know.
